apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
  namespace: argocd
spec:
  destination:
    namespace: dev-v2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes-manifests/dev-v2
    repoURL: https://github.com/gmj06/UdaCityShop
    targetRevision: HEAD
  syncPolicy:
    automated: {}
